; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_ldf_mode = deep+
; 串口监视器与烧录速度
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder ; 开启崩溃自动解码器，极其重要！

; 存储与分区表 (8MB + Huge APP)
board_upload.flash_size = 8MB
board_build.partitions = huge_app.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

; 核心硬件参数覆盖 (匹配 OPI PSRAM)
board_build.arduino.memory_type = qio_opi 

; 编译宏定义
build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0 
    -D CORE_DEBUG_LEVEL=3
    ; 1. 强行打破溢出缓冲池上限！
    -D EI_MAX_OVERFLOW_BUFFER_COUNT=128
    ; 2. 强行指定内存分配模式！
    -D EI_CLASSIFIER_ALLOCATION_METHOD=1
    ; 3. 强行划拨 500KB 超大草稿纸，无视头文件！
    -D EI_CLASSIFIER_TENSOR_ARENA_SIZE=500000